
name: CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest


    steps:

    - uses: actions/checkout@v2

    - name: Install and test
      run: |
        npm install
        npm test
